### ISSUE TITLE
Complete Implementation Demonstration of the project 

### ISSUE THREAD

**Issue by RISHIT-ANAND** [GAR-Project/project#10]
Dear Sir,
I really got interested in your project and wanted to execute it step by step to experience about the D-Dos activities and the classification of packets through AI.

However, i am a windows user currently and am planning to run a Ubuntu terminal through azure and implement it.
I needed your help on the implementation part and a video of the same if possible because the YouTube video in the readme is blocked.

**Comment by davidcawork** [comment]
Hello @RISHIT-ANAND  😃 

I am very glad that you are interested in the project. In it you will be able to find out about SDN network emulation technologies, DDoS attacks, artificial intelligence (just classifiers, in this case, SVM). 

As it says in the documentation the whole project has been focused on Linux environments, different installation methods have been given as you can see in section [Installation methods](https://github.com/GAR-Project/project#installation-methods-wrench). If you want to set up another environment it is at your own discretion. 

As for the video only illustrated how to perform the attack with the tool Hping3, simply followed the steps that are already indicated in the documentation of the repository. So all you have to do is read it and follow it step by step. The video is not available because Youtube has classified it as dangerous since it could be understood that it incited to perform DDoS attacks.

Have a nice day!
