### ISSUE TITLE
About the attack process

### ISSUE THREAD

**Issue by exitclear** [GAR-Project/project#12]
The video link about the DDOS attack cannot be played. How did it work? thank you!

**Comment by davidcawork** [comment]
Hello @exitclear 😸 

The video only illustrated how to perform the attack with the tool Hping3, it simply followed the steps that are already indicated in the documentation of the repository. So all you have to do is read it and follow it step by step. The video is not available because Youtube has classified it as dangerous since it could be understood that it incited to perform DDoS attacks.

Have a nice day!
