### ISSUE TITLE
Error: Vagrant up

### ISSUE THREAD

**Issue by viettd14** [GAR-Project/project#16]
Hello,
i'm learning about ddos sdn, i'm doing the installation according to the instructions but i get an error when i do vagrant up command.
I installed virtualbox, vargrant on ubuntu 18, when I cloned the project and did the vagrant up command. error like below:
==> test: Waiting for machine to boot. This may take a few minutes...
    test: SSH address: 127.0.0.1:2222
    test: SSH username: vagrant
    test: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by davidcawork** [comment]
Hello @viettd14 

Probably what is happening is that your machine is limited in resources and is taking a long time to raise the instance, exceeding the limit set in `config.vm.boot_timeout`. Are you able to raise another instance type in vagrant?  Did you manage to solve it? 

I'm going to close the issue, since it's been a long time, feel free to open it again if the problem persists.
