### ISSUE TITLE
What is the username and password for the controller and test VM?

### ISSUE THREAD

**Issue by jackinhub** [GAR-Project/project#3]
Hi David,
I repeat your project, try to get it run on my computer. There are some issues that I could not find a clue. There is no private_key file in the folder. 

Regards,
Jack

**Comment by davidcawork** [comment]
Hi Jack 😄 ,

Can you please provide more info about your scenario? And more important, What method have you followed to install our project?

Best,

**Comment by jackinhub** [comment]
Hi David,

Thank you for the quick prompt. Sure. I installed a virtualbox Ubuntu 16.04 VM and get the test and controller VMs nested. I find the username and password, but still failed to SSH. Probably because the private_key file  is not in the folder. I have not tried to set up the SSH to bypass the problem yet. Just wondering why the private_key is not generated with your code.

Cheers,

**Comment by davidcawork** [comment]
Hi Jack 😄 ,

As far as I understand (correct me if I'm wrong), your scenario is a virtual machine, and inside it, you have manually created two virtual machines (test, controller) with Virtualbox.

I understand that you have followed the [native](https://github.com/GAR-Project/project#native) installation steps, and you have run the shellscripts on each machine. In this installation method, unlike the vagrant installation method, SSH key management is not configured as Vagrant does for us.  One of the strengths of Vagrant is that it takes care of the generation of a key pair for us, puts the public one on the machine it is deploying, and sets the path of the private one (`.vagrant/machines/{vm_name}/virtualbox/private_key`), so we can connect to that machine doing a `vagrant ssh {vm_name}` or `ssh -i .vagrant/machines/{vm_name}/virtualbox/private_key vagrant@{vm_IP}`. Therefore, since you have followed another installation method, you do not have the key pairs to connect to them via SSH. 

How could you do the key configuration yourself ? I would do it in the following way 😺 :


```shell

# Generate a pair of keys
ssh-keygen

# At this point you can set a name for your key pair, depending on the name you enter, 
# two files will be generated: name_entered (private one) and name_entered.pub (public one).

# You have to change the permissions of the keys, so that ssh does not consider them insecure.
chmod 600 name_entered.pub name_entered 

# Now that you have the generated keys, you will need to log into each VM, and deposit the generated public key. 
# Ideally, you should generate a pair of keys for each VM. Whatever you prefer. In case you do not have installed a ssh server 
# in each VM, you have to install it: sudo apt install -y openssh-server 

# Open this file, or create it. And paste the the PUBLIC one inside 
sudo vim /home/{user}/.ssh/authorized_keys

# At this point you could connect via ssh to the VM by doing so:
ssh -i name_entered {user}@{vm_IP}
```

I hope I have clarified your doubts, 😼

**Comment by jackinhub** [comment]
Thanks David. I followed the vagrant method. The problem could be the speed of the deployment of the two nested VMs (about 20 minutes to boot up). It was timed out for a couple of times. And the key was not generated automatically. I will try it again, and get back to you.

**Comment by davidcawork** [comment]
Hi @jackinhub, 

I understand that the issue would be resolved. If you continue to have problems I encourage you to re-open it, or open a new one if a different issue persists. 😄
