### ISSUE TITLE
Implementation step problem

### ISSUE THREAD

**Issue by ITSTD3999** [GAR-Project/project#8]
Dear All,,
 
I'm having a simple problem regarding this project that is knowing the exact sequence of steps that I have to do
Unfortunately the YouTube video which is submitted in the documentation is deleted because of YouTube's community rules, if you can kindly please send me the instruction manual video regarding this project in order to gain knowledge and implement it , it would me much appreciated

Best Regards

**Comment by ITSTD3999** [comment]
Dear Pablo, 

My first problem regarding this project is how to install vagrant and how to use the vagrant file,
Secondly, i have 2 VM'S both of them are ubuntu's , i want to install mininet how i can do it inside ubuntu and also what to do with the other VM and how to use wireshark

if all the steps of the implementation are in a video it will be great if you can send me the link

**Comment by pcolladosoto** [comment]
Hi @ITSTD3999! I'm afraid your question is way too general: it warrants a full blown article of its own!

I'd recommend you begin by getting to know Vagrant. You can take a look at the [docs](https://www.vagrantup.com/docs). You can also take a look at [this](https://phoenixnap.com/kb/vagrant-beginner-tutorial) tutorial. These documents should clear up your questions regarding how to install *Vagrant* and use the *Vagrantfile*.

Questions regarding 'what to do' with the other VM could maybe be answered by reading [this](https://github.com/GAR-Project/project#our-scenario) section of our documentation. You can also benefit from reading the whole document though.

Now, if you're trying to install Mininet on your own VMs you can draw inspiration from [this](https://github.com/GAR-Project/project/blob/master/util/install_mininet.sh) script we have written. This is actually executed within a VM when provisioning them by running `vagrant up`.

Learning how to use WireShark takes a lot of time and, more importantly, an intricate knowledge of networking in general and networking protocols in particular. You can take a look at [this](https://www.lifewire.com/wireshark-tutorial-4143298) tutorial, but it shouldn't take long to find a myriad of others. However, be warned you'll get very little from WireShark unless you have a grasp of what it is you're really looking at.

Even though the documentation references videos at some point, these have all been taken down by YouTube because they apparently infringed some policies. Nonetheless, these videos added **nothing** to the documentation you can find on the [README](https://github.com/GAR-Project/project/blob/master/README.md). They just showcased some running attacks... Now, even though this is a completely personal opinion I often find written documents to be much more concise and ripe with information. We really believe everything will be much clearer after reading the README, we promise.

If you have any further questions feel free to fire away. However, if they are as general as the ones above I'm afraid we'll be of little help...

I hope you found this at least a bit helpful. Good luck and never ever give up. It can be a bit daunting at times, but I'm sure with time you'll look back and smile at all this 'nonsense' 😜

**Comment by ITSTD3999** [comment]
Hello Pablo, thank you for your response I'm very grateful for the information provided by you
 I'll watch the tutorials and implement the steps, also if a problem came up that is not so general I'll be in touch 

Best Regards

**Comment by pcolladosoto** [comment]
Hi! Best of luck with all that and, as you said, feel free to open a new issue should more specific questions arise at some point.

I'm gonna go ahead and close this issue to keep the repo tidy. Once again, feel free to follow up on any topics on a new issue.

Happy reading 🤓
